{
 "title": "Scout - Drill down",
 "tags": [
  "dell",
  "idrac",
  "redfish",
  "hpe",
  "ilo"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redfish_up,instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "redfish_system_health_state{instance=\"$instance\"}",
     "legendFormat": "{{status}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Chassis Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_chassis_health{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Power",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "redfish_system_power_state{instance=\"$instance\"}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "timestamp(redfish_up) % 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Storage I/O utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "RAID controller",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_chassis_model_info{instance=\"$instance\",chassis_id=~\".*RAID.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "redfish_system_total_memory_size{instance=\"$instance\"}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processor threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(redfish_system_processor_total_threads{instance=\"$instance\"})",
     "legendFormat": "{{state}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redfish_system_storage_drive_capacity{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "redfish_chassis_model_info{instance=\"$instance\",chassis_id!~\".*RAID.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_up{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processor sockets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "redfish_system_total_processor_count{instance=\"$instance\"}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(redfish_storage_drive_capacity{instance=\"$instance\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "BMC",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "redfish_manager_health_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_manager_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_manager_power_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    { "expr": "redfish_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Health",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redfish_system_health_state{instance=\"$instance\"}",
     "legendFormat": "System"
    },
    {
     "expr": "max(redfish_chassis_health{instance=\"$instance\"})",
     "legendFormat": "Chassis"
    },
    {
     "expr": "redfish_manager_health_state{instance=\"$instance\"}",
     "legendFormat": "BMC"
    },
    {
     "expr": "max(redfish_chassis_fan_health{instance=\"$instance\"})",
     "legendFormat": "Fans"
    },
    {
     "expr": "redfish_system_total_memory_health_state{instance=\"$instance\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "redfish_system_total_processor_health_state{instance=\"$instance\"}",
     "legendFormat": "Processors"
    },
    {
     "expr": "max(redfish_system_pcie_device_health_state{instance=\"$instance\"})",
     "legendFormat": "PCIe devices"
    },
    {
     "expr": "max(redfish_chassis_power_powersupply_health{instance=\"$instance\"})",
     "legendFormat": "Power supplies"
    },
    {
     "expr": "max(redfish_chassis_network_port_health_state{instance=\"$instance\"})",
     "legendFormat": "Network ports"
    },
    {
     "expr": "max(redfish_system_storage_drive_health_state{instance=\"$instance\"})",
     "legendFormat": "Storage drives"
    },
    {
     "expr": "max(redfish_chassis_temperature_sensor_health{instance=\"$instance\"})",
     "legendFormat": "Temperature sensors"
    }
   ]
  },
  {
   "title": "Storage volumes",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "redfish_system_storage_volume_capacity{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_storage_volume_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_storage_volume_health_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory modules",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "redfish_system_memory_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_memory_capacity{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_memory_health_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 20 },
   "targets": [
    {
     "expr": "redfish_chassis_fan_health{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage drives",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "redfish_system_storage_drive_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_storage_drive_health_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_storage_drive_capacity{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIe devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "redfish_system_pcie_device_health_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_pcie_device_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_pcie_function_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_pcie_function_health_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 28 },
   "targets": [
    {
     "expr": "redfish_system_processor_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_processor_health_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 28 },
   "targets": [
    {
     "expr": "redfish_chassis_temperature_sensor_health{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network ports",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "redfish_chassis_network_port_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_chassis_network_port_health_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_chassis_network_port_link_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethernet interfaces",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 36 },
   "targets": [
    {
     "expr": "redfish_system_ethernet_interface_link_status{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_ethernet_interface_link_enabled{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redfish_system_ethernet_interface_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thermal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time(redfish_chassis_temperature_celsius{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{sensor}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Fans",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time(redfish_chassis_fan_rpm{instance=~\"$instance\",}[$__rate_interval])",
       "legendFormat": "{{fan}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Power Supplies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max_over_time(redfish_chassis_power_powersupply_power_output_watts{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Output PSU-{{id}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "avg_over_time(redfish_chassis_power_powersupply_power_output_watts{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Input PSU-{{id}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "redfish_chassis_power_powersupply_power_capacity_watts{instance=~\"$instance\"}",
     "legendFormat": "__auto",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "(timestamp(redfish_up{instance=\"$instance\"}) * 70 % 100 ) * 5",
     "legendFormat": "{{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Voltage - Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "redfish_chassis_power_voltage_volts{instance=\"$instance\",power_voltage=~\".*MEM.*\"} > 0",
     "legendFormat": "{{power_voltage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Voltage - CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "redfish_chassis_power_voltage_volts{instance=\"$instance\",power_voltage=~\".*VCORE.*\"} > 0",
     "legendFormat": "{{power_voltage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Voltage - Power Supplies",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "redfish_chassis_power_voltage_volts{instance=\"$instance\",power_voltage=~\".*PS.*\"} > 0",
     "legendFormat": "{{power_voltage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}