{
 "title": "Scout - Overview",
 "tags": [
  "dell",
  "idrac",
  "redfish",
  "hpe",
  "ilo"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(idrac_system_machine_info,job)"
   },
   {
    "name": "instance",
    "query": "label_values(idrac_system_machine_info{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"health_state\", redfish_system_health_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"health_state\", redfish_chassis_health)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Physical Security Sensor",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"health_state\", redfish_chassis_physical_security_sensor_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"health_state\", redfish_system_total_processor_health_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BMC",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"health_state\", redfish_manager_health_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"health_state\", redfish_system_total_memory_health_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health state history",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "redfish_system_health_state",
     "legendFormat": "{{instance}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Warning and critical servers",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "redfish_system_health_state{instance=~\"$instance\"} >=2",
     "legendFormat": "{{instance}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System pool health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "count(redfish_system_health_state == 1) / count(redfish_system_health_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thermal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature Inlet - Top 10",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "topk(10, avg_over_time(redfish_chassis_temperature_celsius{instance=~\"$instance\",sensor=~\".*Inlet.*|.*Ambient.*\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      },
      {
       "expr": "avg(avg_over_time(redfish_chassis_temperature_celsius{instance=~\"$instance\", sensor=~\".*Inlet.*|.*Ambient.*\"}[$__rate_interval]))",
       "legendFormat": "Mean: Inlet"
      }
     ]
    },
    {
     "title": "Temperature Outlet - Top 10",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg(avg_over_time(redfish_chassis_temperature_celsius{instance=~\"$instance\",sensor=~\".*Out.*|.*Exhaust.*\"}[$__rate_interval]))",
       "legendFormat": "Mean: Outlet"
      },
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "topk(10, avg_over_time(redfish_chassis_temperature_celsius{instance=~\"$instance\", sensor=~\"Out.+|.*Exhaust.*\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Temperature - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "redfish_chassis_temperature_celsius{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Temperature CPU - Top 10",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 14, "x": 10, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "topk(10, avg(redfish_chassis_temperature_celsius{sensor=~\".*CPU.*\"}) by (instance))",
       "legendFormat": "{{instance}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      },
      {
       "expr": "avg(avg_over_time(redfish_chassis_temperature_celsius{sensor=~\".*CPU.*\"}[$__rate_interval]))",
       "legendFormat": "Mean: CPU temp"
      }
     ]
    },
    {
     "title": "Fans - Fastest, Slowest",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "bottomk(10,avg_over_time(redfish_chassis_fan_rpm{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}: {{fan}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "topk(10,avg_over_time(redfish_chassis_fan_rpm{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}: {{fan}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Fans - Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "targets": [
      { "expr": "redfish_chassis_fan_rpm{}", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power state",
     "type": "state-timeline",
     "gridPos": { "h": 14, "w": 9, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "redfish_system_power_state",
       "legendFormat": "{{instance}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Power Consumption (total)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 15, "x": 9, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "topk(10,avg(redfish_chassis_power_average_consumed_watts{instance=~\"$instance\"}) by (instance))",
       "legendFormat": "{{instance}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Power Consumption - Highest, Lowest",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "topk(10,avg_over_time(redfish_chassis_power_average_consumed_watts{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "bottomk(10,avg_over_time(redfish_chassis_power_average_consumed_watts{instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Power Supplies (output)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "max_over_time(redfish_chassis_power_powersupply_power_output_watts{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}: Output PSU-{{id}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}