# flagger/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flagger-system
spec:
  releaseName: flagger
  chart:
    spec:
      chart: flagger
      version: "1.38.0" 
      sourceRef:
        kind: HelmRepository
        name: flagger
  interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    meshProvider: kubernetes
    prometheus:
      install: false
      
    metricsServer: "http://prometheus-kube-prometheus-prometheus.monitoring:9090"
    
    