apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/flagger
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flagger-system
