apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 10m
  path: ./kustomize/kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: flagger
  targetNamespace: flagger-system
  timeout: 2m
