apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespace-dev
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/namespace-dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: dev
  timeout: 2m
